language: node_js

node_js:
  - '6'
  - '8'

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.37.40-64bit bash
before_script:
  - docker exec -it emscripten bash .build-emscripten.sh
  - yarn run dist-test
script:
  - yarn lint
  - yarn run test-es6
  - yarn run test-dist
  - yarn run test-parity
  - yarn run prettier && git diff --exit-code
  - yarn cover
after_success:
  - npm install -g coveralls
  - cat coverage/lcov.info | coveralls
