name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Test Node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [6, 8, 10, 14]

    steps:
      - uses: actions/checkout@v2.1.1

      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node_version }}'

      - name: Setup Yarn
        run: |
          mkdir -p "$HOME/.yarn/bin"
          curl -L -o "$HOME/.yarn/bin/yarn" https://github.com/yarnpkg/yarn/releases/download/v1.22.10/yarn-1.22.10.js
          chmod +x "$HOME/.yarn/bin/yarn"
          export PATH="$HOME/.yarn/bin:$PATH"

      - name: Tests
        run: |
          yarn --ignore-engines
          yarn test-fast

  # Run the full CI suite for Node 12. Tests are expected to pass for all Node versions,
  # but the build only needs to work for the development version, which should match the
  # Volta config in package.json
  test-full:
    name: Full Test Node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [12]

    steps:
      - uses: actions/checkout@v2.1.1

      - uses: actions/setup-node@v2
        with:
          node-version: '${{ matrix.node_version }}'

      - name: Setup Docker
        run: |
          yarn
          yarn docker-boot
          yarn build-emscripten

      - name: Tests
        run: |
          yarn lint
          yarn test-fast
          yarn check-prettier
          yarn check-docs
          yarn check-tsd
          yarn cover

      - name: Coverage
        run: |
          npm install -g coveralls
          nyc report --reporter=text-lcov | coveralls
